[book]
authors = ["haruki7049 <tontonkirikiri@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "kakei Documentation"
description = "Documentation for kakei - A kakeibo (household financial ledger) CLI application"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/haruki7049/kakei"
edit-url-template = "https://github.com/haruki7049/kakei/edit/main/docs/book/{path}"
site-url = "/kakei/"
default-theme = "light"
preferred-dark-theme = "navy"
